### ISSUE TITLE
Period filter

### ISSUE THREAD

**Issue by jason-p-pickering** [dhis2/datim-dedupe#16]
Hi Mark,
You brought this up the other day, about the need to have a period filter. Was just wondering what this should do. Should we return all records which are contained within the supplied period, meaning if we supply "2013Oct" would this be all records ONLY for this period, or all records which are contained within the startdate and enddate of this period?

**Comment by Markionium** [comment]
I mentioned it because it was initially one of the "filters" in the ui mockup i got. So i'm just answering this based on my knowledge from what i've heard.

I'm not really sure what this should be. I guess we will have to look at the workflow for this. When exactly is dedupe going to happen? If it were to happen say monthy or daily or half yearly then one could select that period and dedupe for that period. (From what i can guess though it will be before the reporting periods so 2 times per year or so)

If like you say it will be between the start date/end date then perhaps picking period type is not really needed but we only need to have the user pick a date instead of a period type and a period. Then indeed wecan just provide a date to the sql. Since in that case the period type itself is not really important.
