### ISSUE TITLE
Cannot resolve duplicates 

### ISSUE THREAD

**Issue by jason-p-pickering** [dhis2/datim-dedupe#28]
Procedure to reproduce. Login to test.datim.org and select the dedupe app. 

1) Select Zambia. 
2) Select Targets
3) Select October 2015-September 2016. 

https://test.datim.org/api/sqlViews/IfP5S1xeRlr/data?var=ou:f5RoebaDLMx&var=pe:2015Oct&var=rs:false&var=ps:50&var=pg:1&var=dt:TARGETS

should provide some results. 

You should see some dupes in the app. Attempt to dedupe any of them, and you will get a small orange warning box in upper right hand corner. Nothing seen in Chrome debugging. 

Using Version 41.0.2272.89 (64-bit) Google Chrome on Ubuntu.

**Comment by Markionium** [comment]
Period that used to be returned from the server was used to resolve the duplicate. Since that was not available the period could not be found and so the dedupe would not be saved.

Since now the period on the client side will be used (as it's always the same for the dedupes on screen) this should be resolved.
